package slddoc

import (
	"bytes"
	"strings"
	"testing"
)

// realPictureSVG is real xsde2svg output for shapes 11 and 12
// (sld-svg/examples/test/Test_12_PictureFile.svg, base64 payloads cut
// short): bare <image> tags with no id or data-type.
const realPictureSVG = `<?xml version="1.0"?>
<!-- Generated by xsde2svg v.1.4.19 with SVGo -->
<svg width="940" height="490"
     style='stroke-width: 0px; background-color: #f5ebeb;'
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
<!-- подложка:11 -->
<image x="770" y="90" width="40" height="30" xlink:href="data:image/jpeg;base64,iVBORw0KGgo=" />
<!-- картинка_файл:12 -->
<image x="60" y="110" width="20" height="20" xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRg==" />
</svg>`

func TestExtract_RealPictures(t *testing.T) {
	d, report, err := Extract([]byte(realPictureSVG), "test", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Failed) != 0 || len(report.Skipped) != 0 {
		t.Errorf("report = %+v", report)
	}
	if len(d.Elements) != 2 {
		t.Fatalf("elements = %d, want 2", len(d.Elements))
	}
	want := []struct {
		points []Point
		href   string
	}{
		{[]Point{{770, 90}, {810, 120}}, "data:image/jpeg;base64,iVBORw0KGgo="},
		{[]Point{{60, 110}, {80, 130}}, "data:image/jpeg;base64,/9j/4AAQSkZJRg=="},
	}
	ids := map[int]bool{}
	for i, el := range d.Elements {
		if el.Class != ClassPicture || el.Shape != "11" {
			t.Errorf("element %d: class/shape = %s/%s", i, el.Class, el.Shape)
		}
		if el.ID == 0 || ids[el.ID] {
			t.Errorf("element %d: id %d not a fresh synthesized id", i, el.ID)
		}
		ids[el.ID] = true
		if len(el.Points) != 2 || el.Points[0] != want[i].points[0] || el.Points[1] != want[i].points[1] {
			t.Errorf("element %d: points = %v, want %v", i, el.Points, want[i].points)
		}
		if el.Href != want[i].href {
			t.Errorf("element %d: href = %q, want %q", i, el.Href, want[i].href)
		}
	}
}

// TestRender_Picture: Static writes the source's own bare <image> (nothing
// without an image) and reads back through Extract; Interactive never
// carries the href and shows a dashed frame when there is no image.
func TestRender_Picture(t *testing.T) {
	const href = "data:image/png;base64,iVBORw0KGgo="
	pic := Element{ID: 7, Class: ClassPicture, Shape: "11", Name: "logo", Points: []Point{{100, 50}, {60, 20}}, Href: href}
	empty := Element{ID: 8, Class: ClassPicture, Shape: "11", Points: []Point{{0, 0}, {10, 10}}}
	d := &Diagram{Width: 200, Height: 200, Elements: []Element{pic, empty}}
	lib := NewSymbolLibrary(nil)

	var buf bytes.Buffer
	if err := Render(d, lib, &buf, Static, "", nil); err != nil {
		t.Fatal(err)
	}
	static := buf.String()
	wantTag := `<image id="7" x="60" y="20" width="40" height="30" xlink:href="` + href + `" data-name="logo" data-type="11" />`
	if !strings.Contains(static, wantTag) {
		t.Errorf("Static: want %s in\n%s", wantTag, static)
	}
	if strings.Contains(static, `id="8"`) {
		t.Errorf("Static: a Picture without an image should draw nothing:\n%s", static)
	}
	back, report, err := Extract([]byte(static), "test", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Failed) != 0 || len(back.Elements) != 1 {
		t.Fatalf("round trip: report %+v, elements %+v", report, back.Elements)
	}
	if got := back.Elements[0]; got.ID != 7 || got.Name != "logo" || got.Href != href || got.Points[0] != (Point{60, 20}) || got.Points[1] != (Point{100, 50}) {
		t.Errorf("round trip = %+v", got)
	}

	frags, err := RenderFragments(d, lib, []int{7, 8}, Interactive, "", nil)
	if err != nil {
		t.Fatal(err)
	}
	if f := frags[7]; strings.Contains(f, "href") || !strings.Contains(f, `<image x="60" y="20" width="40" height="30" />`) || !strings.Contains(f, `data-editor-kind="element"`) {
		t.Errorf("Interactive with image = %s", f)
	}
	if f := frags[8]; !strings.Contains(f, "stroke-dasharray") || strings.Contains(f, "<image") {
		t.Errorf("Interactive without image = %s", f)
	}
}

// TestSaveLoad_PictureHref: Href is saved as an <image> child and only on
// the element that has one.
func TestSaveLoad_PictureHref(t *testing.T) {
	const href = "data:image/png;base64,iVBORw0KGgo="
	d := &Diagram{Width: 10, Height: 10, Elements: []Element{
		{ID: 1, Class: ClassPicture, Shape: "11", Points: []Point{{0, 0}, {10, 10}}, Href: href},
		{ID: 2, Class: ClassBreaker, Shape: "41"},
	}}
	var buf bytes.Buffer
	if err := d.Save(&buf); err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(buf.String(), "<image>"); n != 1 {
		t.Errorf("<image> count = %d, want 1:\n%s", n, buf.String())
	}
	back, err := Load(&buf)
	if err != nil {
		t.Fatal(err)
	}
	if back.Elements[0].Href != href || back.Elements[1].Href != "" {
		t.Errorf("hrefs = %q, %q", back.Elements[0].Href, back.Elements[1].Href)
	}
}
